# Generated by Django 5.2.1 on 2025-06-15 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nikki', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='useranime',
            name='status',
            field=models.CharField(choices=[('toWatch', 'To Watch'), ('watching', 'Watching'), ('finished', 'Finished')], max_length=20),
        ),
    ]
