# Generated by Django 5.2.1 on 2025-06-15 22:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nikki', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='season',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='season',
            name='anime',
        ),
        migrations.AddField(
            model_name='anime',
            name='mal_id',
            field=models.IntegerField(default=0, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='episode',
            name='anime',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to='nikki.anime',
                null=True
            ),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='useranime',
            name='status',
            field=models.CharField(choices=[('toWatch', 'To Watch'), ('watching', 'Watching'), ('finished', 'Finished')], max_length=20),
        ),
        migrations.DeleteModel(
            name='UserSeasonView',
        ),
        migrations.RemoveField(
            model_name='episode',
            name='season',
        ),
        migrations.DeleteModel(
            name='Season',
        ),
        migrations.AlterUniqueTogether(
            name='episode',
            unique_together={('anime', 'episode_number')},
        ),
    ]
