# Generated by Django 5.2.1 on 2025-06-15 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nikki', '0002_alter_user_avatar_alter_user_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='synopsis_fr',
            field=models.TextField(blank=True),
        ),
    ]
