# Generated by Django 5.2.1 on 2025-05-30 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nikki', '0002_alter_user_avatar_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='mal_id',
            field=models.IntegerField(default=999999, unique=True),
            preserve_default=False,
        ),
    ]
