# Generated by Django 5.2.1 on 2025-06-15 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nikki', '0003_anime_synopsis_fr'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='title_fr',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
