# Generated by Django 5.2.1 on 2025-06-16 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nikki', '0004_episode_title_fr'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='nb_episodes',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
