# Generated by Django 5.2.1 on 2025-06-17 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nikki', '0005_anime_nb_episodes'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='duration',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='watch_time',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
