name: Run Django Tests

on:
  pull_request:
    branches: [ master ]

jobs:
  test:
    name: Django Tests
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_DB: test_db
          POSTGRES_USER: test_user
          POSTGRES_PASSWORD: test_pass
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      DB_NAME: test_db
      DB_USER: test_user
      DB_PASSWORD: test_pass
      DB_HOST: localhost
      DB_PORT: 5432
      DJANGO_SETTINGS_MODULE: config.settings

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest-playwright
        playwright install --with-deps

    - name: Run migrations
      run: python manage.py migrate

    - name: Run Django unit/integration tests
      run: python manage.py test nikki.tests

    - name: Run Django dev server in background
      run: |
        nohup python manage.py runserver 0.0.0.0:8000 &
        sleep 5

    - name: Run Playwright E2E tests
      run: pytest nikki/tests/e2e/ --browser chromium
